VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IExpPlugin"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

'IExpPlugin.cls: interface for BCSearch plugins.

'current support is rudimentary- currently it supports a single method- "FileSelectionChange".


Public Sub FileSelectionChange(SelectedItems As Collection, SearchForm As Object)
'
End Sub
